### ISSUE TITLE
Headers in different rows

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/hra-kg#4]
For the ASCT+B tables for ureter and urinary bladder (v1.0), it was reported to us that the headers start in a row different from row 10, where they normally start. This is probably a leftover from the ASCT+B table format from v1.0. This should be corrected in 7th release by GUDMAP team. I encouraged them to NOT use raw ASCT+B tables ever but would like to keep a record of this comment.

**Comment by bherr2** [comment]
Actually, according to the spec, there isn't a strict limit on the number of header rows. The spec says that the first row with a column named "AS/1" is where the header rows end and the data begins.
