### ISSUE TITLE
Fix heart 3d crosswalk row

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-kg#5]
```#VHMHeart,#VHMaleOrgans,VH_M_papillary_muscle_of_heart_anterolateral,Anterolateral head of lateral papillary muscle of left ventricle,FMA:7265,http://purl.org/sig/ont/fma/fma72655,VH_M_Heart```

https://github.com/hubmapconsortium/hra-kg/blob/main/digital-objects/ref-organ/asct-b-3d-models-crosswalk/v1.5/raw/asct-b-3d-models-crosswalk.csv#L1726

Above has an extra 5.. http://purl.org/sig/ont/fma/fma72655 => http://purl.org/sig/ont/fma/fma7265

Remove the extra five and update the 3d model asociated with it.

**Comment by emquardokus** [comment]
Found another one that we're fixing: 
Both were in male heart 
Posterior papillary muscle of right ventricle FMA:7261 
Removed extra "1" http://purl.org/sig/ont/fma/fma72611==>http://purl.org/sig/ont/fma/fma7261

**Comment by emquardokus** [comment]
**Other crosswalk issues being fixed for 7th release June 15, 2024**
1) main lactiferous duct had uberon number UBERON:0015134 
but fma iri http://purl.org/sig/ont/fma/fma62102==> http://purl.obolibrary.org/obo/UBERON_0015134

**Comment by emquardokus** [comment]
New column called "Node type" is being added to 3d crosswalk to distinguish different types of scene nodes: 
Values can be organizational, mesh, or surface
