### ISSUE TITLE
Update Left/Right Ovary Ref Organ to use new Uberon terms

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-kg#8]
Our ovary ref organs use FMA terms for Left Ovary and Right Ovary. Uberon recently added more resolution to ovary codes, with UBERON:0002119 for left ovary and UBERON:0002118 for right ovary. There might be some issues in switching, but let's look into it.

CC @emquardokus 
FYI @AlanSimmons

**Comment by emquardokus** [comment]
@bherr2 updated 3D ref model crosswalk ---will this update in RUI and EUI?  We are agnostic to side in ASCT+B tables for all organs with laterality: kidney, ovary, fallopian tube, ureter, lung etc.
Data portal organ page is agnostic to laterality of organ for ovary. https://portal.hubmapconsortium.org/organ/ovary

**Comment by bherr2** [comment]
@emquardokus yes, the RUI and EUI will be updated with those. Won't be automatic, but we can make it happen as part of the release in December.
